version: '3'

services:
  db:
    image: postgres:9.6.3
    environment:
      - POSTGRES_USER=linkely
      - POSTGRES_DB=linkely

  es:
    image: elasticsearch:7.10.1
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  web:
    build: docker/web/
    volumes:
      - .:/src:ro
      - static:/static:rw
    command: /src/entrypoint.sh
    ports:
      - "8000:8000"
    environment:
      - "POSTGRES_HOST=db"
      - "ES_HOST=es"
      - "STATIC_ROOT=/static"
    depends_on:
      - db
      - es
      - memcached

  web_static:
    image: sebp/lighttpd
    ports:
      - "8001:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.static_web.entrypoints=websecure"
      - "traefik.http.routers.static_web.tls=true"
      - "traefik.http.routers.static_web.tls.certresolver=myresolver"
      - "traefik.http.routers.static_web.rule=Host(`linkely.com`)"
    networks:
      - proxy
    volumes:
      - static:/var/www/localhost/htdocs:ro
      - $PWD/docker/static_web/:/etc/lighttpd:ro
    tty: true

  memcached:
    image: memcached:1.6.9-alpine
    ports:
      - "11211:11211"

volumes:
  static:

networks:
  proxy:
    external:
      name: "traefik_proxy"
