version: '3'

services:
  db:
    image: postgres:9.6.3
    environment:
      - POSTGRES_USER=linkely
      - POSTGRES_DB=linkely
    ports:
      - "5432:5432"

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.0
    ports:
      - "9200:9200"
    environment:
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  web:
    image: python:3.9.1
    volumes:
      - .:/src:ro
    command: /src/entrypoint.sh
    ports:
      - "8000:8000"
    depends_on:
      - db
      - es

  nginx:
    image: nginx:1.13.3
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./linkely/static:/data/www/static
    ports:
      - "80:80"
    depends_on:
      - web
