version: '3'

services:
  db:
    image: postgres:9.6.3
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: unless-stopped

  es:
    image: elasticsearch:7.10.1
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    restart: unless-stopped

  memcached:
    image: memcached:1.6.9-alpine
    ports:
      - "11211:11211"
    restart: unless-stopped

  web:
    build: docker/web/
    volumes:
      - .:/src:ro
      - static:/static:rw
    command: /src/entrypoint.sh
    ports:
      - "8000:8000"
    environment:
      - "POSTGRES_HOST=db"
      - "ES_HOST=es"
      - "STATIC_ROOT=/static"
    depends_on:
      - db
      - es
      - memcached
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.linkely.entrypoints=websecure"
      - "traefik.http.routers.linkely.tls=true"
      - "traefik.http.routers.linkely.tls.certresolver=myresolver"
      - "traefik.http.routers.linkely.rule=Host(`linkely.co`)"
      - "traefik.http.middlewares.compress-traffic.compress=true"
      - "traefik.http.routers.linkely.middlewares=compress-traffic"
      - "traefik.http.services.linkely.loadbalancer.server.port=8000"
    links:
      - "db:db"
      - "es:es"
      - "memcached:memcached"
      
    networks:
      - default
      - traefik_proxy

    restart: unless-stopped

  web_static:
    image: sebp/lighttpd

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.linkely_static.entrypoints=websecure"
      - "traefik.http.routers.linkely_static.tls=true"
      - "traefik.http.routers.linkely_static.tls.certresolver=myresolver"
      - "traefik.http.routers.linkely_static.rule=Host(`static.linkely.co`)"
      - "traefik.http.middlewares.compress-static.compress=true"
      - "traefik.http.routers.linkely_static.middlewares=compress-static"
      - "traefik.http.services.linkely_static.loadbalancer.server.port=80"
    networks:
      - default
      - traefik_proxy
    volumes:
      - static:/var/www/localhost/htdocs:ro
      - $PWD/docker/static_web/:/etc/lighttpd:ro
    tty: true

    restart: unless-stopped

volumes:
  static:

networks:
  traefik_proxy:
    external: true
