version: '3'

services:
  db:
    image: mysql
    environment:
      # TODO: Manage secrets in a better way
      - MYSQL_ROOT_PASSWORD=YWNiminE8SMQ
  # web:
  #   build: .
  #   command: python3 manage.py runserver 0.0.0.0:8000
  #   volumes:
  #     - .:/code
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - db
