version: '3'

services:
  db:
    image: postgres:9.6.3
    environment:
      - POSTGRES_USER=linkely
      - POSTGRES_DB=linkely
    ports:
      - "5432:5432"

  es:
    image: elasticsearch:7.10.1
    ports:
      - "9200:9200"
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  web:
    build: docker/web/
    volumes:
      - .:/src:ro
    command: /src/entrypoint.sh
    ports:
      - "8000:8000"
    environment:
      - "POSTGRES_HOST=db"
      - "ES_HOST=es"
    depends_on:
      - db
      - es
      - memcached

  nginx:
    image: nginx:1.13.3
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./linkely/static:/data/www/static
    ports:
      - "80:80"
    depends_on:
      - web

  memcached:
    image: memcached:1.6.9-alpine
    ports:
      - "11211:11211"
