# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('url', models.URLField(max_length=500)),
                ('description', models.TextField()),
                ('tags', models.CharField(max_length=50)),
                ('date', models.DateTimeField(verbose_name='date added')),
            ],
        ),
    ]
